# Generated by Django 5.0.1 on 2024-01-08 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_question_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
