# Generated by Django 5.0.1 on 2024-01-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogloszenia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamieszczanieogloszen',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
