# Generated by Django 5.0.1 on 2024-01-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogloszenia', '0002_zamieszczanieogloszen_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamieszczanieogloszen',
            name='dataAktualizacji',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='zamieszczanieogloszen',
            name='markaPojazdu',
            field=models.CharField(choices=[('A', 'Audi'), ('A', 'Alfa Romeo'), ('A', 'Aston Martin'), ('B', 'Bentley'), ('B', 'BMW'), ('B', 'Bugatti'), ('C', 'Cadillac'), ('C', 'Chevrolet'), ('C', 'Chrysler'), ('C', 'Citroen'), ('D', 'Dodge'), ('F', 'Ferrari'), ('F', 'Fiat'), ('F', 'Ford'), ('G', 'GMC'), ('G', 'Genesis'), ('H', 'Honda'), ('H', 'Hyundai'), ('I', 'Infiniti'), ('J', 'Jaguar'), ('J', 'Jeep'), ('K', 'Kia'), ('L', 'Lamborghini'), ('L', 'Lexus'), ('L', 'Lincoln'), ('M', 'Mazda'), ('M', 'Maserati'), ('M', 'Mercedes-Benz'), ('M', 'Mini'), ('M', 'Mitsubishi'), ('N', 'Nissan'), ('O', 'Opel'), ('P', 'Peugeot'), ('P', 'Porsche'), ('R', 'Ram'), ('R', 'Renault'), ('S', 'Skoda'), ('S', 'Smart'), ('S', 'Subaru'), ('S', 'Suzuki'), ('T', 'Tesla'), ('T', 'Toyota'), ('V', 'Volkswagen'), ('V', 'Volvo')], max_length=50),
        ),
    ]
